# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170928_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qusetion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='qusetion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qusetion_text',
            new_name='question_text',
        ),
    ]
